create table user_list (
	id SERIAL,
	name TEXT,
	college TEXT
);

insert into user_list (name, college) values ('Meghan Titmus', 'Troy University');
insert into user_list (name, college) values ('Justino Neil', 'Raghebe Esfahani University');
insert into user_list (name, college) values ('Vera Avey', 'University of Central Lancashire');
insert into user_list (name, college) values ('Westbrooke Laurencot', 'Nippon Dental University');
insert into user_list (name, college) values ('Alfi Prenty', 'Dibrugarh University');
insert into user_list (name, college) values ('Karleen Tibb', 'Post University of Waterbury');
insert into user_list (name, college) values ('Mathilda Skrzynski', 'Hebei Academy of Fine Art');
insert into user_list (name, college) values ('Darline Nicholl', 'Anadolu University');
insert into user_list (name, college) values ('Debee Bulmer', 'Capitol College');
insert into user_list (name, college) values ('Vanya Andrivel', 'Universitas Ngurah Rai');
insert into user_list (name, college) values ('Frannie Gionettitti', 'Perm State Pharmaceutical Academy');
insert into user_list (name, college) values ('Travers Rawsthorne', 'Dartmouth College');
insert into user_list (name, college) values ('Aurelie Headley', 'Ecole Nationale Supérieure d''Ingénieurs en Mécanique et Energétique de Valenciennes');
insert into user_list (name, college) values ('Emmalyn Gianullo', 'University of Trnava');
insert into user_list (name, college) values ('Brittan McIlvoray', 'Kangnam University');
insert into user_list (name, college) values ('Uriah Hundall', 'SASTRA Deemed University');
insert into user_list (name, college) values ('Berkley Wallworth', 'De Montfort University Leicester');
insert into user_list (name, college) values ('Mortie Escudier', 'Zhejiang Forestry University');
insert into user_list (name, college) values ('Jerrold Dominichelli', 'Universidad del Magdalena');
insert into user_list (name, college) values ('Anabelle Brownett', 'Mount Sinai School of Medicine');
insert into user_list (name, college) values ('Cesar Patey', 'Kobe Pharmaceutical University');
insert into user_list (name, college) values ('Maribel Gerlack', 'Russel Sage College');
insert into user_list (name, college) values ('Kelsi Fulop', 'Université de Bouaké');
insert into user_list (name, college) values ('Gweneth Forte', 'Universidad San Marcos');
insert into user_list (name, college) values ('Emelda Manuelli', 'American Graduate School in Paris');
insert into user_list (name, college) values ('Ursula Upham', 'Suranaree University of Technology');
insert into user_list (name, college) values ('Murielle Cherrett', 'Central Christian College of the Bible');
insert into user_list (name, college) values ('Kyrstin Dalbey', 'California Institute of Technology');
insert into user_list (name, college) values ('Sarge Gresswell', 'Polotsk State University');
insert into user_list (name, college) values ('Tracy Addicott', 'Kagawa Institute of Nutrition');
insert into user_list (name, college) values ('Heall Slopier', 'Indian Institute of Science');
insert into user_list (name, college) values ('Jane Raimbauld', 'Ecole d''Ingénieurs en Informatique pour l''Industrie');
insert into user_list (name, college) values ('Anny Harvie', 'Göteborg University');
insert into user_list (name, college) values ('Erek Paulat', 'Technische Universität Dresden');
insert into user_list (name, college) values ('Erick Durban', 'Universidad Distral "Francisco José de Caldas"');
insert into user_list (name, college) values ('Petunia Rothert', 'Kurdistan University of Medical Sciences');
insert into user_list (name, college) values ('Zenia Struttman', 'University of Delaware');
insert into user_list (name, college) values ('Wilfrid Ambler', 'Beth-El College of Nursing and Health Sciences');
insert into user_list (name, college) values ('Julita Wolfendell', 'Meiji University of Oriental Medicine');
insert into user_list (name, college) values ('Berne Struijs', 'El Shorouk Academy');
insert into user_list (name, college) values ('Kelley Elcome', 'Walailak University');
insert into user_list (name, college) values ('Artur Althrop', 'Huston-Tillotson College');
insert into user_list (name, college) values ('Nissy Mackerel', 'Institut des Sciences de la Matière et du Rayonnement');
insert into user_list (name, college) values ('Nikita Bentham', 'Thunderbird School of Global Management');
insert into user_list (name, college) values ('Torie Cochrane', 'IMPAC University');
insert into user_list (name, college) values ('Mar Jentle', 'Alaska Pacific University');
insert into user_list (name, college) values ('Flora Malby', 'Universidad Nacional de Lomas de Zamora');
insert into user_list (name, college) values ('Hestia Corson', 'Gifu University for Education and Languages');
insert into user_list (name, college) values ('Roddy Sibbering', 'Universidad ORT Uruguay');
insert into user_list (name, college) values ('Prudy Duddy', 'Fachhochschule Münster');
insert into user_list (name, college) values ('Shaylah Haugg', 'Eastern Conservatory of Music');
insert into user_list (name, college) values ('Gabriel Bletcher', 'University of Texas Southwestern Medical Center at Dallas');
insert into user_list (name, college) values ('Ken Mufford', 'European Graduate School, Media & Communications');
insert into user_list (name, college) values ('Aubry Haine', 'International University of Novi Pazar');
insert into user_list (name, college) values ('Geri Barajaz', 'Sevastopol National Technical University');
insert into user_list (name, college) values ('Sybilla Dalton', 'Pyongtaek University ');
insert into user_list (name, college) values ('Shelly Conelly', 'University College of Arts, Crafts and Design');
insert into user_list (name, college) values ('Worthington Dymidowski', 'Moldova Cooperative Trade University');
insert into user_list (name, college) values ('Maritsa Etoile', 'Instituto Superior de Assistentes e Intérpretes');
insert into user_list (name, college) values ('Ebonee Eley', 'Universidad Columbia del Paraguay');
insert into user_list (name, college) values ('Jillane Jurs', 'Merz Akademie, Hochschule für Gestaltung Stuttgart');
insert into user_list (name, college) values ('Rubie Spavon', 'Universiti Pendidikan Sultan Idris');
insert into user_list (name, college) values ('Fabio Acosta', 'Susquehanna University');
insert into user_list (name, college) values ('Orella Dundendale', 'South China Agricultural University');
insert into user_list (name, college) values ('Rolfe Dufore', 'Manchester College');
insert into user_list (name, college) values ('Gabriele Crow', 'Divine Word College of Legazpi');
insert into user_list (name, college) values ('Marla Arkle', 'Catholic University of Lublin');
insert into user_list (name, college) values ('Joseph Nagle', 'National Sports Academy Sofia');
insert into user_list (name, college) values ('Othella Siggin', 'Baker College of Cadillac');
insert into user_list (name, college) values ('Astrix Parkinson', 'Academy of Economic Studies of Moldova');
insert into user_list (name, college) values ('Bayard Gentric', 'Abfi Institute Perbanas Jakarta');
insert into user_list (name, college) values ('Netti Hunting', 'European University Institute');
insert into user_list (name, college) values ('Morrie Hesbrook', 'Université Paul Valéry (Montpellier III)');
insert into user_list (name, college) values ('Frazer Hobell', 'Institut Textile et Chimique de Lyon');
insert into user_list (name, college) values ('Tony Cassius', 'Hong Kong Institute of Education');
insert into user_list (name, college) values ('Rosy Dearden', 'Cumberland College');
insert into user_list (name, college) values ('Frieda Gashion', 'Philosophisch-Theologisches Studium Erfurt, Staatlich anerkannte Wissenschaftliche Hochschule');
insert into user_list (name, college) values ('Itch Corwin', 'Technical University of Bialystok');
insert into user_list (name, college) values ('Dante Burr', 'The Defiance College');
insert into user_list (name, college) values ('Raquel Canaan', 'University of Qatar');
insert into user_list (name, college) values ('Sheppard Chaundy', 'Universidad San Francisco de Quito');
insert into user_list (name, college) values ('Griselda Loomis', 'Edgewood College');
insert into user_list (name, college) values ('Tynan Tuvey', 'The Naropa Institute');
insert into user_list (name, college) values ('Ealasaid Baldassi', 'Universidad Católica Santa María La Antigua');
insert into user_list (name, college) values ('Boyce Wakeling', 'Brunswick Community College');
insert into user_list (name, college) values ('Othilie Jahnisch', 'University of Teesside');
insert into user_list (name, college) values ('Webster Trotter', 'COMSATS Institute of Information Technology, Wah');
insert into user_list (name, college) values ('Kimmi Pawelec', 'Universidad Politécnica de Valencia');
insert into user_list (name, college) values ('Alix Mourant', 'University of Nicosia');
insert into user_list (name, college) values ('Francine Edwin', 'Catholic University in Zimbabwe');
insert into user_list (name, college) values ('Burnaby Chanter', 'Lebanese American University');
insert into user_list (name, college) values ('Parker Vane', 'Foundation University');
insert into user_list (name, college) values ('Jazmin Steagall', 'Paul University');
insert into user_list (name, college) values ('Hermine Dymond', 'DeSales University');
insert into user_list (name, college) values ('Ralph Starkings', 'Universidad Salesiana de Bolivia');
insert into user_list (name, college) values ('Raphaela Starking', 'Arlington Baptist College');
insert into user_list (name, college) values ('Morty Broadbear', 'Sylhet Engineering College');
insert into user_list (name, college) values ('Thorny Stockford', 'Monash University, Malaysia Campus');
insert into user_list (name, college) values ('Iosep Fender', 'Hainan Normal University');
insert into user_list (name, college) values ('Maurita Vezey', 'Birmingham City University');
insert into user_list (name, college) values ('Granville Nix', 'Scripps College');
insert into user_list (name, college) values ('Tann Vaillant', 'St. Petersburg State Theatre Arts Academy');
insert into user_list (name, college) values ('Gennie Langworthy', 'Yukon College');
insert into user_list (name, college) values ('Joellyn Fritz', 'James Madison University');
insert into user_list (name, college) values ('Greggory Sorbey', 'Kyoto Seika University');
insert into user_list (name, college) values ('Vinny Spira', 'Institute of Teachers Education, Rajang');
insert into user_list (name, college) values ('Byram Sumpton', 'Fundación Universitaria Manuela Beltrán');
insert into user_list (name, college) values ('Chen Felton', 'Barclay College');
insert into user_list (name, college) values ('Brigit Calcott', 'Shizuoka Sangyo University');
insert into user_list (name, college) values ('Veronique Folliss', 'Wadi International University');
insert into user_list (name, college) values ('Koenraad Pinder', 'Cyryx College');
insert into user_list (name, college) values ('Lindi Wiz', 'University of Maine, Machias');
insert into user_list (name, college) values ('Rosabella Hoggetts', 'Birsa Agricultural University');
insert into user_list (name, college) values ('Stephine Earley', 'Ningxia University');
insert into user_list (name, college) values ('Bryce Keher', 'Universidad Internacional de Integración de América Latina');
insert into user_list (name, college) values ('Gilly Vasiljevic', 'Merz Akademie, Hochschule für Gestaltung Stuttgart');
insert into user_list (name, college) values ('Rudy Groom', 'Xi''an Highway University');
insert into user_list (name, college) values ('Stanly Blas', 'Islamic Azad University, Shirvan');
insert into user_list (name, college) values ('Elsie Calveley', 'William Carey College');
insert into user_list (name, college) values ('Fancie Godspeede', 'Saint Ferdinand College');
insert into user_list (name, college) values ('Xylia Burnhill', 'Universidad Nacional de San Juan');
insert into user_list (name, college) values ('Bibbye Paulig', 'University of Novi Sad');
insert into user_list (name, college) values ('Rriocard Gowdridge', 'Asian Management Institute');
insert into user_list (name, college) values ('Mady Cattermole', 'Qinghai University');
insert into user_list (name, college) values ('Lottie Eggleton', 'Universidade para o Desenvolvimento do Alto Vale do Itajaí');
insert into user_list (name, college) values ('Richardo Chastan', 'Fachhochschule Bochum');
insert into user_list (name, college) values ('Fidela Saing', 'High Point University');
insert into user_list (name, college) values ('Cristen Rafter', 'College of Management');
insert into user_list (name, college) values ('Cecil Rassell', 'Smith College');
insert into user_list (name, college) values ('Nari Stubbeley', 'University of Split');
insert into user_list (name, college) values ('Hube Shambrooke', 'Hochschule Bremen');
insert into user_list (name, college) values ('Adena Anniwell', 'Naif Arab University for Security Sciences');
insert into user_list (name, college) values ('Gery Biagini', 'Universidade Aberta Lisboa');
insert into user_list (name, college) values ('Giovanni Gainor', 'Norwegian College of Veterinary Medicine');
insert into user_list (name, college) values ('Manon Wickstead', 'Fujita Health University');
insert into user_list (name, college) values ('Kitty Parlot', 'Kyoto Prefectural University of Medicine');
insert into user_list (name, college) values ('Odie Petriello', 'Manchester College');
insert into user_list (name, college) values ('Ettore Carluccio', 'Ukrainian Academy of Pharmacy');
insert into user_list (name, college) values ('Iggy Langrish', 'Kwame Nkrumah University of Science and Technology');
insert into user_list (name, college) values ('Elva Malec', 'Algonquin College');
insert into user_list (name, college) values ('Gunar Shillabeer', 'Turar Ryskulov Kazakh Economic University');
insert into user_list (name, college) values ('Thornton Riccardi', 'Colorado State University-Pueblo');
insert into user_list (name, college) values ('Avril Weins', 'Fachhochschule Mainz');
insert into user_list (name, college) values ('Travers Bruinsma', 'St. Francis Xavier University');
insert into user_list (name, college) values ('Lila Geratt', 'Universidad Nacional Experimental "Rafael Maria Baralt"');
insert into user_list (name, college) values ('Melisandra Hovard', 'University of Maine (System)');
insert into user_list (name, college) values ('Darin Shovelbottom', 'University of Illinois at Springfield');
insert into user_list (name, college) values ('Johann Klementz', 'Ohio Northern University');
insert into user_list (name, college) values ('Carie Jura', 'Urmia University of Technology');
insert into user_list (name, college) values ('Rora Strutley', 'Instituto Superior Politécnico Gaya');
insert into user_list (name, college) values ('Doralyn Tumulty', 'John Marshall Law School');
insert into user_list (name, college) values ('Reilly Timbs', 'Universidad de Puerto Rico, Bayamon');
insert into user_list (name, college) values ('Killie Jenk', 'MCI-Management Center Innsbruck');
insert into user_list (name, college) values ('Lian Nerheny', 'Bard College');
insert into user_list (name, college) values ('Adele Nowlan', 'Université de Mons-Hainaut');
insert into user_list (name, college) values ('Amii Stangoe', 'Fachhochschule Rottenburg, Hochschule für Forstwirtschaft');
insert into user_list (name, college) values ('Solomon Eberz', 'Hawaii Pacific University');
insert into user_list (name, college) values ('Franz Tuxill', 'Universidad Cientifica del Sur');
insert into user_list (name, college) values ('Brita Pugsley', 'Nippon Sport Science University');
insert into user_list (name, college) values ('Ronald Orneblow', 'Centenary College of Louisiana');
insert into user_list (name, college) values ('Marjory Crick', 'Darul Hikmah Islamic College');
insert into user_list (name, college) values ('Odele Chooter', 'International College of the Cayman Islands');
insert into user_list (name, college) values ('Lin Simco', 'Ibrahim Babangida University');
insert into user_list (name, college) values ('Ianthe Deeley', 'Universiti Kuala Lumpur Malaysian Institute of Information Technology (MIIT)');
insert into user_list (name, college) values ('Karlotta Ruddoch', 'Instituto Nacional de Educación Física "General Manuel Belgrano"');
insert into user_list (name, college) values ('Raychel Skeech', 'Poole Gakuin University');
insert into user_list (name, college) values ('Aryn Depka', 'Institute of Teachers Education, Dato'' Razali Ismail ');
insert into user_list (name, college) values ('Brianne Beattie', 'Chuka University');
insert into user_list (name, college) values ('Ilyssa McMenamin', 'Universidad de Congreso');
insert into user_list (name, college) values ('Marinna Dayton', 'University of Northampton');
insert into user_list (name, college) values ('Tory Krystof', 'University of Connecticut Health Center');
insert into user_list (name, college) values ('Marni Andryushin', 'Beykent University');
insert into user_list (name, college) values ('Jamal Putley', 'Asian Medical Institute');
insert into user_list (name, college) values ('Barclay Worboy', 'University of South Carolina - Spartanburg');
insert into user_list (name, college) values ('Bel Kiggel', 'Morioka College');
insert into user_list (name, college) values ('Valentijn Danilishin', 'Université de Bretagne Sud');
insert into user_list (name, college) values ('Hatty Hewson', 'University of El Imam El Mahdi University');
insert into user_list (name, college) values ('Lisbeth Jarrad', 'University of Jammu');
insert into user_list (name, college) values ('Bari Sauniere', 'Miyagi University');
insert into user_list (name, college) values ('Thibaut Theriot', 'Aichi Sangyo University');
insert into user_list (name, college) values ('Sigismund Drummer', 'Eastern Washington University');
insert into user_list (name, college) values ('Alyse Faughey', 'University of Oxford');
insert into user_list (name, college) values ('Ervin Flann', 'Preston University, Pakistan Campus');
insert into user_list (name, college) values ('Belle Baudain', 'Sinnar University');
insert into user_list (name, college) values ('Sonya Moules', 'Ecole Normale Supérieure de Paris');
insert into user_list (name, college) values ('Samson Fraschetti', 'Golestan University of Medical Sciences');
insert into user_list (name, college) values ('Rabbi Brandle', 'People'' s Friendship University of Russia');
insert into user_list (name, college) values ('Layne Dockrey', 'American Public University');
insert into user_list (name, college) values ('Janeczka Normant', 'Engineering Colleges in Tamil Nadu');
insert into user_list (name, college) values ('Bridie Ashtonhurst', 'Pomona College');
insert into user_list (name, college) values ('Pinchas Corns', 'Universitat Pompeu Fabra');
insert into user_list (name, college) values ('Cob Dart', 'Mongolian State University of Education');
insert into user_list (name, college) values ('Antonie Richley', 'European Open University');
insert into user_list (name, college) values ('Theodora McKerrow', 'Far Eastern State Technical University');
insert into user_list (name, college) values ('Grissel Dudin', 'Hachinohe University');
insert into user_list (name, college) values ('Pierette Helm', 'University of Portland');
insert into user_list (name, college) values ('Grissel Longbothom', 'Jawzjan University');
insert into user_list (name, college) values ('Florella Guirardin', 'Cape Peninsula University of Technology');
insert into user_list (name, college) values ('Rowan Fitzsimon', 'Harding University Graduate School of Religion');
insert into user_list (name, college) values ('Geno Haskett', 'Bulacan State University');
insert into user_list (name, college) values ('Prue Rowe', 'Ecole Nationale de la Statistique et de l''Analyse de l''information');
insert into user_list (name, college) values ('Lewes Pickover', 'Universitas Proklamasi 45');
insert into user_list (name, college) values ('Adriaens Fozzard', 'University of Szczecin');
insert into user_list (name, college) values ('Wally Colnett', 'Kobe Pharmaceutical University');
insert into user_list (name, college) values ('Ricardo Ilyinski', 'Chaminade University of Honolulu');
insert into user_list (name, college) values ('Clea Le Floch', 'United Arab Emirates University');
insert into user_list (name, college) values ('Dino Cornbill', 'Coastal Carolina University');
insert into user_list (name, college) values ('Murray Faucherand', 'Azerbaijan National Conservatorie');
insert into user_list (name, college) values ('Steward Ockenden', 'University of Engineering and Technology Taxila');
insert into user_list (name, college) values ('Karita Bernardinelli', 'National Taiwan College of the Arts');
insert into user_list (name, college) values ('Wendie Knappitt', 'College of Idaho');
insert into user_list (name, college) values ('Halette Wenger', 'Salahddin University (Kurdistan Region)');
insert into user_list (name, college) values ('Zondra Murrhardt', 'Al-Azhar University of Gaza');
insert into user_list (name, college) values ('Maurene Glackin', 'Lawrence Technological University');
insert into user_list (name, college) values ('Ddene Worvill', 'Ashton College');
insert into user_list (name, college) values ('Johnette Gouch', 'École des Hautes Études Commerciales');
insert into user_list (name, college) values ('Trefor Manoelli', 'Rikkyo University (St. Paul''s University)');
insert into user_list (name, college) values ('Sybille Gandrich', 'University of Health Sciences');
insert into user_list (name, college) values ('Cooper Sherebrooke', 'Central State University');
insert into user_list (name, college) values ('Chic Hurt', 'Aichi University of Education');
insert into user_list (name, college) values ('Karlotta Whorton', 'University of the Philippines Diliman');
insert into user_list (name, college) values ('Cara Reede', 'Johnson & Wales University');
insert into user_list (name, college) values ('Ann-marie Gawne', 'Universidade Tecnica de Lisboa');
insert into user_list (name, college) values ('Hall Sehorsch', 'Prairie View Agricultural and Mechanical University');
insert into user_list (name, college) values ('Vito Collingham', 'Arizona State University, Polytechnic Campus');
insert into user_list (name, college) values ('Spenser Dicky', 'John Carroll University');
insert into user_list (name, college) values ('Sammy Hockell', 'Université de Toamasina');
insert into user_list (name, college) values ('Elayne Vandenhoff', 'Mahatma Jyotiba Phule Rohilkhand University Bareilly ');
insert into user_list (name, college) values ('Hope Godsal', 'Georgia Southern University');
insert into user_list (name, college) values ('Delphinia Tilbey', 'University of North Carolina at Chapel Hill');
insert into user_list (name, college) values ('Karen Clemmett', 'Foundation University');
insert into user_list (name, college) values ('Catherin Darrow', 'Schiller International University, Heidelberg');
insert into user_list (name, college) values ('Reagen McGann', 'Gujarat University Ahmedabad');
insert into user_list (name, college) values ('Trenton McNickle', 'Eötvös Lorand University');
insert into user_list (name, college) values ('Hermann Torrent', 'Tamil Nadu Dr. Ambedkar Law University');
insert into user_list (name, college) values ('Titus Bawcock', 'University of Modern Sciences');
insert into user_list (name, college) values ('Peder Eakley', 'Technological Education Institute of Epiros');
insert into user_list (name, college) values ('Babbie Cassely', 'Concordia University, Portland');
insert into user_list (name, college) values ('Tierney Sussams', 'Dongduk Women''s University');
insert into user_list (name, college) values ('Joelie Dunbobbin', 'Cornell College');
insert into user_list (name, college) values ('Blinni Pinchen', 'Fachhochschule Bingen');
insert into user_list (name, college) values ('Ferguson Linner', 'Yanbu University College');
insert into user_list (name, college) values ('Adelaide Martschke', 'Al Nahrain University');
insert into user_list (name, college) values ('Andrey Mitkov', 'Universidad ISALUD');
insert into user_list (name, college) values ('Darell Avon', 'International University of Southern Europe');
insert into user_list (name, college) values ('Rey Giacobo', 'Solusi University');
insert into user_list (name, college) values ('Verne Gilligan', 'China University of Mining Technology - Beijing');
insert into user_list (name, college) values ('Saloma Burchfield', 'Columbia College');
insert into user_list (name, college) values ('Mendel Alban', 'Feati University');
insert into user_list (name, college) values ('Karia Roan', 'Moldova Technical University');
insert into user_list (name, college) values ('Maurits Elphick', 'Université de Bandundu Ville');
insert into user_list (name, college) values ('Brit Peagram', 'Holy Spirit University of Kaslik');
insert into user_list (name, college) values ('Erma Ickovic', 'National Chung Cheng University');
insert into user_list (name, college) values ('Aldis Noquet', 'KBU International College');
insert into user_list (name, college) values ('Binny Raysdale', 'Shimer College');
insert into user_list (name, college) values ('Nanon MacKimm', 'Gifu Pharmaceutical University');
insert into user_list (name, college) values ('Rey Kasparski', 'School of Design and Crafts');
insert into user_list (name, college) values ('Frannie Merman', 'University of Applied Sciences Basel (FHBB )');
insert into user_list (name, college) values ('Gabriela Blanshard', 'Akwa Ibom State University of Technology');
insert into user_list (name, college) values ('Iosep Iacomelli', 'St. Andrews Presbyterian College');
insert into user_list (name, college) values ('Grove Obee', 'Ecole Nationale Supérieure en Electrotechnique, Electronique, Informatique et Hydraulique de Toulouse');
insert into user_list (name, college) values ('Ebonee Sweeting', 'Far Eastern State Technical Fisheries University');
insert into user_list (name, college) values ('Crissie Daniello', 'University of Windsor');
insert into user_list (name, college) values ('Lavina Sullens', 'Universiti Sultan Zainal Abidin');
insert into user_list (name, college) values ('Madelaine Hallewell', 'Dongseo University');
insert into user_list (name, college) values ('Red Croxton', 'Shaheed Beheshti University');
insert into user_list (name, college) values ('Bevin Langelay', 'Universidad Nacional de Asunción');
insert into user_list (name, college) values ('Ivy Cuddihy', 'Central America Health Sciences University (Belize Medical College)');
insert into user_list (name, college) values ('Carlina Semper', 'Shaw University');
insert into user_list (name, college) values ('Liuka Brinkman', 'Hofstra University');
insert into user_list (name, college) values ('Isa Lenoir', 'King Fahad University of Petroleum and Minerals');
insert into user_list (name, college) values ('Derby Bertin', 'Universidad Francisco de Paula Santander');
insert into user_list (name, college) values ('Shermy Concklin', 'Adventist University of Central Africa');
insert into user_list (name, college) values ('Van Capsey', 'Melaka Islamic University College');
insert into user_list (name, college) values ('Angel Kydd', 'Rajiv Gandhi University');
insert into user_list (name, college) values ('Clotilda Wims', 'Himeji Institute of Technology');
insert into user_list (name, college) values ('Luis De Pero', 'Marian College');
insert into user_list (name, college) values ('Thomasin Inchbald', 'Portland Community College');
insert into user_list (name, college) values ('Giles Cawker', 'Calvary Bible College');
insert into user_list (name, college) values ('Katey Gillebride', 'Universidade Metodista de Piracicaba');
insert into user_list (name, college) values ('Caroljean McDill', 'School of Economic Sciences');
insert into user_list (name, college) values ('Yelena Dioniso', 'Universidad Politecnica de Nicaragua');
insert into user_list (name, college) values ('Jon Bartkiewicz', 'MGH Institute of Health Professions');
insert into user_list (name, college) values ('Shellie Medforth', 'University of Basel');
insert into user_list (name, college) values ('Konstanze Gathwaite', 'Arizona State University, West Campus');
insert into user_list (name, college) values ('Lindy Jaye', 'Johann Wolfgang Goethe Universität Frankfurt am Main');
insert into user_list (name, college) values ('Joleen Winsley', 'Edison Community College');
insert into user_list (name, college) values ('Pepita Davioud', 'Davis and Elkins College');
insert into user_list (name, college) values ('Raphaela Conwell', 'Wawasan Open University');
insert into user_list (name, college) values ('Charity Geggus', 'Universidad del Aconcagua');
insert into user_list (name, college) values ('Buiron Vigar', 'Université Catholique de Lyon');
insert into user_list (name, college) values ('Rhona Stiven', 'Castleton State College');
insert into user_list (name, college) values ('Marya Goutcher', 'Tsuru University');
insert into user_list (name, college) values ('Coreen Izsak', 'Southwestern Assemblies of God University');
insert into user_list (name, college) values ('Masha Malacrida', 'Tianjin Academy of Fine Art');
insert into user_list (name, college) values ('Jean Shorten', 'University of San Carlos');
insert into user_list (name, college) values ('Keri Redgrove', 'Darul Hikmah Islamic College');
insert into user_list (name, college) values ('Ingunna Ditch', 'Alkharj University');
insert into user_list (name, college) values ('Chevalier MacAdam', 'Masaryk University');
insert into user_list (name, college) values ('Wilma Shatliffe', 'Veliko Turnovo University "Cyril and Methodius"');
insert into user_list (name, college) values ('Dal Wassell', 'Umutara Polytechnic');
insert into user_list (name, college) values ('Alika Gibke', 'Universidad de Huánuco');
insert into user_list (name, college) values ('Jocelin Amburgy', 'Wichita State University');
insert into user_list (name, college) values ('Gus Champneys', 'Washington University in St. Louis');
insert into user_list (name, college) values ('Ursala Gallyhaock', 'Korea University');
insert into user_list (name, college) values ('Janet Genny', 'Ritsumeikan Asia Pacific University');
insert into user_list (name, college) values ('Darn Overill', 'Prague College');
insert into user_list (name, college) values ('Scott Pentelo', 'Strayer University');
insert into user_list (name, college) values ('Sydney Bahike', 'European University');
insert into user_list (name, college) values ('Corette Benediktovich', 'Université de Liège');
insert into user_list (name, college) values ('Gayleen Coffin', 'New Jersey Institute of Technology');
insert into user_list (name, college) values ('Robinia Brickstock', 'Busoga University');
insert into user_list (name, college) values ('Wernher Mapledoram', 'California Institute of the Arts');
insert into user_list (name, college) values ('Bliss Swepson', 'Olabisi Onabanjo University ');
insert into user_list (name, college) values ('Maggy O''Connell', 'Glendale University College of Law');
insert into user_list (name, college) values ('Barbabas Wimbridge', 'The Manchester Metropolitan University');
insert into user_list (name, college) values ('Josi Quartly', 'National Kaohsiung Normal University');
insert into user_list (name, college) values ('Balduin Raccio', 'Shanghai Lida Polytechnic Institute');
insert into user_list (name, college) values ('Barbabra Richardes', 'University of Illinois at Chicago');
insert into user_list (name, college) values ('Hersch Greatland', 'Henan Buddhist College');
insert into user_list (name, college) values ('Lauren Cleynman', 'Poznan University of Life Sciences');
insert into user_list (name, college) values ('Reena Portlock', 'Nigde University');
insert into user_list (name, college) values ('Chicky Spillane', 'University of Opole');
insert into user_list (name, college) values ('Jeramey Ledster', 'DeVry Institute of Technology, Chicago');
insert into user_list (name, college) values ('Donalt Gammidge', 'Osaka Gakuin University');
insert into user_list (name, college) values ('Garey Stollard', 'State University of New York College at Cortland');
insert into user_list (name, college) values ('Ira Cochran', 'Hanoi University of Architecture');
insert into user_list (name, college) values ('Nonna Terbrug', 'University of Art and Design Helsinki');
insert into user_list (name, college) values ('Sibbie Waddell', 'Kyushu Institute of Design');
insert into user_list (name, college) values ('Dorena Goodered', 'Private Fachhochschule für Wirtschaft und Technik Vechta/Diepholz');
insert into user_list (name, college) values ('Mead Biggam', 'McNeese State University');
insert into user_list (name, college) values ('Herve Dawber', 'Manhattan School of Music');
insert into user_list (name, college) values ('Marna McMeekan', 'Omdurman Ahlia University');
insert into user_list (name, college) values ('Gayler Umpleby', 'Universidad de Hermosillo');
insert into user_list (name, college) values ('Ely Bontoft', 'Fachhochschule Gelsenkirchen');
insert into user_list (name, college) values ('Ertha Keneleyside', 'University of Louisiana at Lafayette');
insert into user_list (name, college) values ('Marlow Ick', 'California Coast University');
insert into user_list (name, college) values ('Roanne Langman', 'National Taiwan University of Science and Technology');
insert into user_list (name, college) values ('Rycca Fullalove', 'Universidade Católica de Brasília');
insert into user_list (name, college) values ('Leigh Trenholme', 'St. Petersburg State Technical University');
insert into user_list (name, college) values ('Brodie Juleff', 'Taylor''s University College');
insert into user_list (name, college) values ('Thurston Brabham', 'Universidad Nacional de Río Cuarto');
insert into user_list (name, college) values ('Vivian Hamblett', 'Agricultural University of Lublin');
insert into user_list (name, college) values ('Markos Ludlam', 'Central University for Nationalities');
insert into user_list (name, college) values ('Modesta Rigler', 'Doshisha University');
insert into user_list (name, college) values ('Hirsch Pariso', 'Uppsala University');
insert into user_list (name, college) values ('Marita Maudlen', 'Université Euro-Afrique');
insert into user_list (name, college) values ('Louie Gobat', 'Don Mariano Marcos Memorial State University');
insert into user_list (name, college) values ('Jamal Lackeye', 'Ural State Academy of Railway Transport');
insert into user_list (name, college) values ('Charmine Hawney', 'National University');
insert into user_list (name, college) values ('Crystal Haffard', 'Karaganda State Technical University');
insert into user_list (name, college) values ('Rubetta Ravenshear', 'Manonmaniam Sundaranar University');
insert into user_list (name, college) values ('Nickey Murphey', 'University of New Caledonia');
insert into user_list (name, college) values ('Mag Marlen', 'Catholic University of Malawi');
insert into user_list (name, college) values ('Cosme Quinnelly', 'Tottori University of Environmental Studies');
insert into user_list (name, college) values ('Brenna Deam', 'Tokyo University');
insert into user_list (name, college) values ('Elroy Priest', 'Yashawantrao Chavan Maharashtra Open University');
insert into user_list (name, college) values ('Morie Jupe', 'Moscow State Institute of Radiotechnics, Electronics and Automation (Technical University)');
insert into user_list (name, college) values ('Elmer Huyge', 'Université Paul Sabatier (Toulouse III)');
insert into user_list (name, college) values ('Bobbye White', 'The New College');
insert into user_list (name, college) values ('Andree Rutherforth', 'St. Petersburg State Mining Institute (Technical University)');
insert into user_list (name, college) values ('Gibb Pladen', 'Edogawa University');
insert into user_list (name, college) values ('Claudell Paulig', 'Fachhochschule Weihenstephan');
insert into user_list (name, college) values ('Frank Sergent', 'Rajasthan Vidyapeeth University');
insert into user_list (name, college) values ('Vivi Stanman', 'Université de 7 Novembre à Carthage');
insert into user_list (name, college) values ('Tony Fernant', 'International Institute for Population Sciences');
insert into user_list (name, college) values ('Burch Magrannell', 'Universidad Cardenal Herrera-CEU');
insert into user_list (name, college) values ('Maressa Blow', 'University of Nottingham, Malaysia Campus');
insert into user_list (name, college) values ('Mitchael Balsillie', 'Facultés Universitaires Saint-Louis');
insert into user_list (name, college) values ('Sunny Pyatt', 'Iranian Academy of Persian Language and Literature');
insert into user_list (name, college) values ('Sidney Bakesef', 'Mount Allison University');
insert into user_list (name, college) values ('Loise Dowrey', 'Dhaka International University');
insert into user_list (name, college) values ('Halette Southerill', 'Pjatigorsk State Linguistic University');
insert into user_list (name, college) values ('Stephani Michelmore', 'Ulaanbaatar University');
insert into user_list (name, college) values ('Megan Brinson', 'Bethel College Newton');
insert into user_list (name, college) values ('Marlene Screech', 'Cevro Institut College');
insert into user_list (name, college) values ('West Oiller', 'Visvesvaraya National Institute of Technology');
insert into user_list (name, college) values ('Dniren Haslegrave', 'College of Visual Arts');
insert into user_list (name, college) values ('Irwin Hares', 'University of Bari');
insert into user_list (name, college) values ('Lindsy Robberts', 'Okayama University of Science');
insert into user_list (name, college) values ('Annmarie Tomczak', 'Nova Scotia College of Art and Design');
insert into user_list (name, college) values ('Vanna Aidler', 'University of Pavia');
insert into user_list (name, college) values ('Florette Letixier', 'College of the Holy Cross');
insert into user_list (name, college) values ('Carmella Le Hucquet', 'Tanta University');
insert into user_list (name, college) values ('Wolf Muehler', 'EHSAL - Europese Hogeschool Brussel');
insert into user_list (name, college) values ('Ximenez Gay', 'Qauid-e-Awam University of Engineering Sciences & Technology');
insert into user_list (name, college) values ('Mala Taaffe', 'Nova Scotia Agricultural College');
insert into user_list (name, college) values ('Leigh Elen', 'ITT Technical Institute West Covina');
insert into user_list (name, college) values ('Charisse Gong', 'Universitat de Lleida');
insert into user_list (name, college) values ('Deana Yallowley', 'Universidade do Algarve');
insert into user_list (name, college) values ('Myrwyn Schellig', 'University of Bolton');
insert into user_list (name, college) values ('Gordon Wellington', 'Hyogo University');
insert into user_list (name, college) values ('Beckie Camellini', 'Libyan International Medical University (LIMU)');
insert into user_list (name, college) values ('Iolanthe Breen', 'Chuka University');
insert into user_list (name, college) values ('Quinlan Echallier', 'Fiji School of Medicine');
insert into user_list (name, college) values ('Blancha Frackiewicz', 'Ekiti State University');
insert into user_list (name, college) values ('Read Shetliff', 'Kyushu Dental College');
insert into user_list (name, college) values ('Marta Yakunin', 'Perm State Academy of Agriculture');
insert into user_list (name, college) values ('Reginauld Attwater', 'Karatina University');
insert into user_list (name, college) values ('Aksel Myrick', 'Universidad Mexicana del Noreste');
insert into user_list (name, college) values ('Lodovico Peepall', 'University of Southern Mississippi');
insert into user_list (name, college) values ('Foster Gaitone', 'National Yang Ming Medical College');
insert into user_list (name, college) values ('Jeane Thorrold', 'Symbiosis International University');
insert into user_list (name, college) values ('Doy Lax', 'Blue Mountains Hotel School');
insert into user_list (name, college) values ('Alina Densey', 'Zawiya University');
insert into user_list (name, college) values ('Town Gianinotti', 'Collège Boréal');
insert into user_list (name, college) values ('Dollie Twell', 'Universidad Franco-Mexicana');
insert into user_list (name, college) values ('Sashenka Macak', 'Bunka Women''s University');
insert into user_list (name, college) values ('Sollie Batey', 'University of Medicine Magway');
insert into user_list (name, college) values ('Josepha Harcombe', 'South Gujarat University');
insert into user_list (name, college) values ('Jehanna Battram', 'University of NorthWest');
insert into user_list (name, college) values ('Carol Schechter', 'Universidad Nacional de San Martín');
insert into user_list (name, college) values ('Tess Catherine', 'Hanoi Medical University');
insert into user_list (name, college) values ('Kirbee Seath', 'Asian University of Science and Technology');
insert into user_list (name, college) values ('Shena Syvret', 'Fachhochschule Erfurt');
insert into user_list (name, college) values ('Bibbye Choldcroft', 'European University');
insert into user_list (name, college) values ('Adriana Johns', 'University of Halifax, Birmingham Campus');
insert into user_list (name, college) values ('Gregoire Jeyes', 'Lingnan University');
insert into user_list (name, college) values ('Shae Loghan', 'National American University, Sioux Falls');
insert into user_list (name, college) values ('Case Rabb', 'Sang Myung University');
insert into user_list (name, college) values ('Roseann Ilchenko', 'Texas College');
insert into user_list (name, college) values ('Jan Aspenlon', 'Universidad Autónoma de Chapingo');
insert into user_list (name, college) values ('Alexei Dincey', 'Pwani University');
insert into user_list (name, college) values ('Nancy Rimbault', 'Elizabeth City State University');
insert into user_list (name, college) values ('Currey Bwy', 'Mokwon University Taejon');
insert into user_list (name, college) values ('Vilhelmina Ivoshin', 'Riga Technical University');
insert into user_list (name, college) values ('Catharine MacPike', 'Universidad Mayor');
insert into user_list (name, college) values ('Carson MacShirie', 'Institute of Teachers Education, Sarawak');
insert into user_list (name, college) values ('Kelila Dossetter', 'Osaka University of Education');
insert into user_list (name, college) values ('Anders Warrior', 'Mustafa Kemal University');
insert into user_list (name, college) values ('Hadleigh Ropkes', 'Politeknik Negeri Jakarta');
insert into user_list (name, college) values ('Stern Shakelady', 'Liaoning University');
insert into user_list (name, college) values ('Shirlene Errol', '2nd Military Medical University');
insert into user_list (name, college) values ('Carina Stables', 'Fakir Mohan University');
insert into user_list (name, college) values ('Wenona Dodd', 'Universidade Aberta Lisboa');
insert into user_list (name, college) values ('Job Kellaway', 'Claremont Lincoln University');
insert into user_list (name, college) values ('Sydney Bowne', 'National University of Ostroh Academy');
insert into user_list (name, college) values ('Parke Ordish', 'Ufa State Petroleum Technological University');
insert into user_list (name, college) values ('Shay Mosey', 'Universidade Federal de Ouro Preto');
insert into user_list (name, college) values ('Cheslie Blaik', 'Indiana University at Kokomo');
insert into user_list (name, college) values ('Beverie Lambricht', 'Metropolitan University');
insert into user_list (name, college) values ('Antoinette Abramof', 'Tohoku University of Art and Design');
insert into user_list (name, college) values ('Ealasaid Dunabie', 'Fachhochschule Ulm, Hochschule für Technik');
insert into user_list (name, college) values ('Banky Pearsall', 'Kalinga University');
insert into user_list (name, college) values ('Aeriel Polly', 'University of Applied Sciences of Moldova');
insert into user_list (name, college) values ('Carine Tattershall', 'Ankara University');
insert into user_list (name, college) values ('Robby Lycett', 'Universidade do Estado do Rio Grande do Norte');
insert into user_list (name, college) values ('Gerrilee Bourcq', 'University of San Jose Recoletos');
insert into user_list (name, college) values ('Isadora Densun', 'Institute of Information Technology');
insert into user_list (name, college) values ('Muhammad Patnelli', 'Georgia Health Sciences University');
insert into user_list (name, college) values ('Pooh Mardell', 'Golestan University of Medical Sciences');
insert into user_list (name, college) values ('Kylen Goodwill', 'Victoria University of Wellington');
insert into user_list (name, college) values ('Kylila Mariaud', 'Molde University College');
insert into user_list (name, college) values ('April Goskar', 'Cihan University');
insert into user_list (name, college) values ('Shelby Ravilus', 'Swinburne University of Technology, Sarawak Campus');
insert into user_list (name, college) values ('Caryn Arzu', 'Franklin College Switzerland');
insert into user_list (name, college) values ('Valeria Asel', 'University of Liberia');
insert into user_list (name, college) values ('Nikolos Towhey', 'Kirksville College of Osteopathic Medicine');
insert into user_list (name, college) values ('Lilli Seven', 'Samuel Merritt College');
insert into user_list (name, college) values ('Hall Lenahan', 'Universitas Kristen Duta Wacana');
insert into user_list (name, college) values ('Janeta Clawsley', 'Universidad de Cuautitlan Izcalli');
insert into user_list (name, college) values ('Esta Willicott', 'Universidad Privada del Norte');
insert into user_list (name, college) values ('Rollins Brayfield', 'Katholische Stiftungsfachhochschule München');
insert into user_list (name, college) values ('Dugald Sleit', 'Evangelische Fachhochschule Freiburg, Hochschule für Soziale Arbeit, Diakonie und Religionspädagogik');
insert into user_list (name, college) values ('Nert Rate', 'Kyrgyz Russian Slavic University');
insert into user_list (name, college) values ('Terrye Simoncello', 'Universidade Federal do ABC');
insert into user_list (name, college) values ('Eugenius Pauleit', 'London Business School');
insert into user_list (name, college) values ('Daren Bolderstone', 'Mazandaran University of Iran');
insert into user_list (name, college) values ('Myrtice Penvarden', 'Harokopio University');
insert into user_list (name, college) values ('Waldon Hafford', 'Universidade de Ribeirão Preto');
insert into user_list (name, college) values ('Ruthie Waddell', 'Indian Institute of Information Technology');
insert into user_list (name, college) values ('Morgun Seccombe', 'Full Sail University');
insert into user_list (name, college) values ('Reta Guyer', 'St. Petersburg State Agrarian University');
insert into user_list (name, college) values ('Boot Sam', 'City University of New York, New York City Technical College');
insert into user_list (name, college) values ('Joan Gebby', 'Université de Toulouse');
insert into user_list (name, college) values ('Travis Pinckstone', 'Universidad Privada de Santa Cruz de la Sierra');
insert into user_list (name, college) values ('Dyan Nipper', 'Universidad Autónoma de Centro América');
insert into user_list (name, college) values ('Alvan Abrams', 'University of Liverpool');
insert into user_list (name, college) values ('Laurene Carbonell', 'Hochschule Mittweida (FH)');
insert into user_list (name, college) values ('Bettina Reihm', 'Universidad Católica de Santiago del Estero');
insert into user_list (name, college) values ('Kinsley Stranaghan', 'Kumamoto Institute of Technology');
insert into user_list (name, college) values ('Timothee Steven', 'Enugu State University of Science and Technology');
insert into user_list (name, college) values ('Karim Labdon', 'Postgraduate Institute of Pali & Buddhist Studies (University of Kelaniya)');
insert into user_list (name, college) values ('Casper Davidow', 'Stanford University');
insert into user_list (name, college) values ('Goldi Bohje', 'Chiba University of Commerce');
insert into user_list (name, college) values ('Kristan Flint', 'St. Andrew''s University');
insert into user_list (name, college) values ('Chiarra Dakhov', 'Universidade Federal de Pernambuco');
insert into user_list (name, college) values ('Farris Essex', 'Canakkale (18th March) University');
insert into user_list (name, college) values ('Marena Megahey', 'Okayama University of Science');
insert into user_list (name, college) values ('Ty Lenz', 'Universidade Aberta Lisboa');
insert into user_list (name, college) values ('Vin Leithgoe', 'Bradley University');
insert into user_list (name, college) values ('Kippar Manlow', 'Universidade do Rio Grande');
insert into user_list (name, college) values ('Lyndell O''Kielt', 'American University of the Caribbean, Sint Maarten');
insert into user_list (name, college) values ('Agnola Betterton', 'Helsinki University of Technology');
insert into user_list (name, college) values ('Malanie Penhaleurack', 'Fachhochschulstudiengänge der Wiener Wirtschaft');
insert into user_list (name, college) values ('Spike Thomsen', 'La Salle University');
insert into user_list (name, college) values ('Dieter Dempsey', 'Mount Olive College');
insert into user_list (name, college) values ('Levon Kennifeck', 'Nagoya University');
insert into user_list (name, college) values ('Ray Pailin', 'Adygeja State University');
insert into user_list (name, college) values ('Tarah Cursey', 'Fachhochschule Niederrhein');
insert into user_list (name, college) values ('Kylila Powrie', 'Fachhochschule Neubrandenburg');
insert into user_list (name, college) values ('Daile Lyal', 'University of Texas at San Antonio');
insert into user_list (name, college) values ('Norina Cobbold', 'Islamic University of Gaza');
insert into user_list (name, college) values ('Allie Ringe', 'Universidade de Fortaleza');
insert into user_list (name, college) values ('Ellary Severs', 'Warner Pacific College');
insert into user_list (name, college) values ('Jerri Hyder', 'Bastyr University');
insert into user_list (name, college) values ('Renaldo Shinfield', 'Sabzevar School of Medical Sciences');
insert into user_list (name, college) values ('Sigmund Deniseau', 'Elmergib University');
insert into user_list (name, college) values ('Brennen Drezzer', 'Academy of Art College');
insert into user_list (name, college) values ('Tova Gorioli', 'Western University');
insert into user_list (name, college) values ('Kippie Bottell', 'Instituto Politécnico de Castelo Branco');
insert into user_list (name, college) values ('Ariel McMichell', 'Auburn University at Montgomery');
insert into user_list (name, college) values ('Alexine Swanton', 'Royal School of Library and Information Science');
insert into user_list (name, college) values ('Talyah Hebburn', 'Shimer College');
insert into user_list (name, college) values ('Laurena Flasby', 'Point Loma Nazarene College');
insert into user_list (name, college) values ('Ivar Shillington', 'Karunya Institute Of Technology ( Deemed University)');
insert into user_list (name, college) values ('Thomasa Gatward', 'Universidade Federal da Paraíba');
insert into user_list (name, college) values ('Brita Heed', 'National Taiwan University of Science and Technology');
insert into user_list (name, college) values ('Ellen Drydale', 'Moscow State University M.V. Lomonosov');
insert into user_list (name, college) values ('Dex Elphinston', 'Uzbek State World Languages University');
insert into user_list (name, college) values ('Dorothea Aspinal', 'Truman State University');
insert into user_list (name, college) values ('Waite Whetnell', 'University of Nottingham, Malaysia Campus');
insert into user_list (name, college) values ('Beverlee Tommeo', 'Hanover College');
insert into user_list (name, college) values ('Cody Grimley', 'King''s College');
insert into user_list (name, college) values ('Fair Hocking', 'Qurtuba University of Science and Infromation Technology');
insert into user_list (name, college) values ('Georges Meert', 'Universidad Regional del Sureste');
insert into user_list (name, college) values ('Koo Reolfo', 'Universidad Nacional del Callao');
insert into user_list (name, college) values ('Carolann Brabben', 'University of Connecticut at Avery Point');
insert into user_list (name, college) values ('Crysta Welbeck', 'South Valley University');
insert into user_list (name, college) values ('Heywood Bogeys', 'Universidad Metropolitana de Ciencias de la Educación');
insert into user_list (name, college) values ('Andonis Flemyng', 'West Virginia Wesleyan College');
insert into user_list (name, college) values ('Odette Wissbey', 'Acdemic Center for Law and Business');
insert into user_list (name, college) values ('Solly Thorius', 'Chiang Mai Vocational College');
insert into user_list (name, college) values ('Romola Bonny', 'Universidade Metropolitana de Angola');
insert into user_list (name, college) values ('Babs Geraldo', 'Qafqaz University');
insert into user_list (name, college) values ('Gretna Bland', 'Green University of Bangladesh');
insert into user_list (name, college) values ('Krystyna Rampton', 'Pamir University');
insert into user_list (name, college) values ('Winnah Tout', 'Staatlich anerkannte Fachhochschule für Kunsttherapie');
insert into user_list (name, college) values ('Annnora Ren', 'Hamamatsu University');
insert into user_list (name, college) values ('Sharon Stiegers', 'Central Philippine University');
insert into user_list (name, college) values ('Casper Ccomini', 'Institut National Polytechnique de Lorraine');
insert into user_list (name, college) values ('Olenolin Matterface', 'Goa University');
insert into user_list (name, college) values ('Arne Newstead', 'Rasmussen College, Wisconsin Campuses');
insert into user_list (name, college) values ('Gradeigh Baldery', 'Sophia University');
insert into user_list (name, college) values ('Drucill Canceller', 'Philippine Christian University');
insert into user_list (name, college) values ('Davin Talmadge', 'Université de Mahajanga');
insert into user_list (name, college) values ('Lenna Vasile', 'Afghan University');
insert into user_list (name, college) values ('Lilla O''Bradane', 'Astrakhan State University');
insert into user_list (name, college) values ('Cacilie O''Shields', 'New Era University');
insert into user_list (name, college) values ('Fernando Ropkins', 'Asia University');
insert into user_list (name, college) values ('Hilton Carse', 'Institut Supérieur d''Agriculture Lille');
insert into user_list (name, college) values ('Elora Hagard', 'Kwararafa University');
insert into user_list (name, college) values ('Faina Silcox', 'Hankuk Aviation University');
insert into user_list (name, college) values ('Steven McIlwaine', 'National University of Singapore');
insert into user_list (name, college) values ('Stanley MacGibbon', 'Iowa Wesleyan College');
insert into user_list (name, college) values ('Stephi Cressy', 'Aomori University');
insert into user_list (name, college) values ('Jeffry Blakeney', 'Lincoln University San Francisco');
insert into user_list (name, college) values ('Lilia Eusden', 'Central South University');
insert into user_list (name, college) values ('Gene Christofe', 'Université Chouaib Doukkali');
insert into user_list (name, college) values ('Carmel Dike', 'Appalachian State University');
insert into user_list (name, college) values ('Gillan Losel', 'University of Khartoum');
insert into user_list (name, college) values ('Schuyler Northen', 'Polish-Japanese Institute of Information Technology in Warsaw');
insert into user_list (name, college) values ('Aggi Saer', 'Canisius College');
insert into user_list (name, college) values ('Ikey Kuscha', 'Mount Olive College');
insert into user_list (name, college) values ('Alexandros Pittel', 'Fachhochschule Westküste, Hochschule für Wirtschaft und Technik');
insert into user_list (name, college) values ('Danny Andrivot', 'Conway School of Landscape Design');
insert into user_list (name, college) values ('Marcy Guillem', 'Universidad Autónoma de San Luis Potosí');
insert into user_list (name, college) values ('Immanuel Jovanovic', 'Saratov State Agrarian University');
insert into user_list (name, college) values ('Almeta Creddon', 'Dr. YS Parmar University of Horticulture and Forestry');
insert into user_list (name, college) values ('Dorothy Ackeroyd', 'Bowling Green State University, Firelands');
insert into user_list (name, college) values ('Griffie Bartley', 'Azerbaijan State Oil Academy');
insert into user_list (name, college) values ('Wallis O''Tierney', 'Islamic Azad University, Lahijan');
insert into user_list (name, college) values ('Susanne Ciciotti', 'Kitasato University');
insert into user_list (name, college) values ('Cherie Sainsbury', 'The New School');
insert into user_list (name, college) values ('Jolene Cuckson', 'Universitas Kristen Satya Wacana');
insert into user_list (name, college) values ('Brendin Aprahamian', 'Universidad Internacional del Ecuador');
insert into user_list (name, college) values ('Iosep Gwyneth', 'Shinawatra University');
insert into user_list (name, college) values ('Alisa Geraldez', 'Institut des Hautes Etudes de Management');
insert into user_list (name, college) values ('Brunhilde Eyres', 'University of Akureyri');
insert into user_list (name, college) values ('Ignacius Maltster', 'Southeastern Bible College');
insert into user_list (name, college) values ('Evvie O''Reilly', 'Vassar College');
insert into user_list (name, college) values ('Em Zanolli', 'Kokugakuin University');
insert into user_list (name, college) values ('Tamas Leele', 'City University of New York, New York City Technical College');
insert into user_list (name, college) values ('Reggi Fairholm', 'Asahikawa Medical College');
insert into user_list (name, college) values ('Hestia Neesham', 'Zhejiang Sci-Tech University ');
insert into user_list (name, college) values ('Alisha Rounsefull', 'Burjat State University');
insert into user_list (name, college) values ('Rustin Goddert.sf', 'Comrat State University');
insert into user_list (name, college) values ('Gavan Ivancevic', 'Belarussian State Technological University');
insert into user_list (name, college) values ('Ashlee Lowten', 'Omsk State Pedagogical University');
insert into user_list (name, college) values ('Max McGlue', 'Newschool of Architecture and Design');
insert into user_list (name, college) values ('Packston Gladeche', 'Beijing Petroleum University');
insert into user_list (name, college) values ('Garrek De Wolfe', 'Katholische Fachhochschule Mainz');
insert into user_list (name, college) values ('Kendra Trubshaw', 'The World Islamic Sciences & Education University');
insert into user_list (name, college) values ('Cordie Plumridege', 'Université de Sherbrooke');
insert into user_list (name, college) values ('Sharleen Florez', 'Gomel State Technical University Pavel Sukhoi');
insert into user_list (name, college) values ('Anestassia Burbudge', 'Krasnoyarsk State Technical University');
insert into user_list (name, college) values ('Ruttger Blew', 'International Bible College');
insert into user_list (name, college) values ('Sterne Greensall', 'Guangdong University of Foreign Studies');
insert into user_list (name, college) values ('Percival Reignould', 'College of the Rockies');
insert into user_list (name, college) values ('Pepita Kilbourne', 'Trent University');
insert into user_list (name, college) values ('Claudio Kneel', 'Universidad Técnica "Federico Santa María"');
insert into user_list (name, college) values ('Gussi Towl', 'University of Northern Virginia');
insert into user_list (name, college) values ('Rene Hunnicot', 'Trinity Theological Seminary');
insert into user_list (name, college) values ('Cristian Cocklin', 'Western Oregon University');
insert into user_list (name, college) values ('Melosa Burwell', 'United Nations University');
insert into user_list (name, college) values ('Seumas Prozescky', 'Universidad Tecnológica del Peru');
insert into user_list (name, college) values ('Homerus Note', 'Volgograd State Pedagogical University');
insert into user_list (name, college) values ('Falito Abbado', 'Ecole Nationale Supérieure du Pétrole et des Monteurs');
insert into user_list (name, college) values ('Elinor Pechet', 'Zhengzhou Grain University');
insert into user_list (name, college) values ('Genna Sailor', 'Pennsylvania Academy of the Fine Arts');
insert into user_list (name, college) values ('Elane Wabersich', 'Neumann College');
insert into user_list (name, college) values ('Kelly Flancinbaum', 'Lampang College of Commerce and Technology');
insert into user_list (name, college) values ('Ole McCurry', 'University of Wales, Swansea');
insert into user_list (name, college) values ('Jeni Gemson', 'University of California, Santa Cruz');
insert into user_list (name, college) values ('Carmine Domleo', 'Whitworth College');
insert into user_list (name, college) values ('Austina Froment', 'Karatina University');
insert into user_list (name, college) values ('Hewie Menhci', 'Ecole Supérieure d''Electricité');
insert into user_list (name, college) values ('Zedekiah Marthen', 'Washington State University');
insert into user_list (name, college) values ('Mano Buesden', 'Millersville University of Pennsylvania');
insert into user_list (name, college) values ('Titus Dufore', 'Viterbo College');
insert into user_list (name, college) values ('Merilee Clinnick', 'University of Wollongong');
insert into user_list (name, college) values ('Mirabelle Bowering', 'New Economic School');
insert into user_list (name, college) values ('Essie Thomelin', 'St. Joseph''s College');
insert into user_list (name, college) values ('Claudetta Clemont', 'Vellore Institute of Technology');
insert into user_list (name, college) values ('Ewen Galler', 'Hijiyama University');
insert into user_list (name, college) values ('Arnaldo Dutchburn', 'Universität Osnabrück');
insert into user_list (name, college) values ('Swen Spini', 'College in Sládkovičovo');
insert into user_list (name, college) values ('Danell Le - Count', 'Universidad de Viña del Mar');
insert into user_list (name, college) values ('Rheta Helling', 'Ithaca College');
insert into user_list (name, college) values ('Samson Leate', 'Universidade Estadual do Norte Fluminense');
insert into user_list (name, college) values ('Nikolaus Muckian', 'Eastern Mediterranean University');
insert into user_list (name, college) values ('Winny Harold', 'Sri Lanka Institute of Information Technology (SLIT)');
insert into user_list (name, college) values ('Lois Shepherd', 'Fachhochschule Westküste, Hochschule für Wirtschaft und Technik');
insert into user_list (name, college) values ('Codie Workes', 'School of the Visual Arts');
insert into user_list (name, college) values ('Irvine Breznovic', 'University of Kragujevac');
insert into user_list (name, college) values ('Miltie Arthars', 'Universidad Internacional de Andalucía');
insert into user_list (name, college) values ('Maressa Millea', 'University Medical School of Pécs');
insert into user_list (name, college) values ('Rickie Hawlgarth', 'Sarajevo Film Academy');
insert into user_list (name, college) values ('Free Waterdrinker', 'Université de Blida');
insert into user_list (name, college) values ('Elga Childerhouse', 'Kyushu Tokai University');
insert into user_list (name, college) values ('Shaylah Canon', 'Tabari Institute of Higher Education');
insert into user_list (name, college) values ('Nikkie Rackham', 'Gratz College');
insert into user_list (name, college) values ('Edan Paulin', 'Tai Solarin University of Education');
insert into user_list (name, college) values ('Reece Abramino', 'Obihiro University of Agriculture and Veterinary Medicine');
insert into user_list (name, college) values ('Anica Voff', 'Tokyo National University of Fine Arts and Music');
insert into user_list (name, college) values ('Dewie Aleksankov', 'University of Calgary');
insert into user_list (name, college) values ('Benji Carmel', 'FPT University');
insert into user_list (name, college) values ('Huberto Jedrzejkiewicz', 'Madawalabu University');
insert into user_list (name, college) values ('Goldy Ringrose', 'Beijing International Studies University');
insert into user_list (name, college) values ('Robina Treweek', 'Universitas Ahmad Dahlan');
insert into user_list (name, college) values ('Ardyce Wyndham', 'University of Lucknow');
insert into user_list (name, college) values ('Anabel Linay', 'Ecole Nationale Supérieure de Physique de Grenoble');
insert into user_list (name, college) values ('Kort Pallent', 'Bangladesh University of Textiles');
insert into user_list (name, college) values ('Anne-marie Poulston', 'University of Cagliari');
insert into user_list (name, college) values ('Gibbie Antonescu', 'Great Lakes Christian College');
insert into user_list (name, college) values ('Garrot McCrohon', 'Rust College');
insert into user_list (name, college) values ('Jermain Tipler', 'University of NorthWest');
insert into user_list (name, college) values ('Bartram Bridel', 'Sindh Madressatul Islam University');
insert into user_list (name, college) values ('Thatch Babbidge', 'University of Buckingham');
insert into user_list (name, college) values ('Tiena De Cruce', 'Beijing Language and Culture University');
insert into user_list (name, college) values ('Sinclair Sharrem', 'University of Liberal Arts');
insert into user_list (name, college) values ('Carmina Duiged', 'Odessa State Academy of Construction and Architecture');
insert into user_list (name, college) values ('Bernetta Larking', 'Marymount Manhattan College');
insert into user_list (name, college) values ('Dido Letch', 'Université de Technologie de Troyes');
insert into user_list (name, college) values ('Angie Guiraud', 'Hope International University');
insert into user_list (name, college) values ('Debee Coales', 'Universidad Central');
insert into user_list (name, college) values ('Noellyn Noye', 'University of New Brunswick');
insert into user_list (name, college) values ('Tilda Grinstead', 'Karolinska Institute Stockholm');
insert into user_list (name, college) values ('Sayres Szymonwicz', 'Russel Sage College');
insert into user_list (name, college) values ('Emmeline Androletti', 'Chungnam National University');
insert into user_list (name, college) values ('Elyn Vaudrey', 'Shahed University');
insert into user_list (name, college) values ('Mackenzie MacGruer', 'American International University West Africa');
insert into user_list (name, college) values ('Borden Thunnerclef', 'National Aviation Academy');
insert into user_list (name, college) values ('Patton Ace', 'Marshall University');
insert into user_list (name, college) values ('Arabelle Scupham', 'Montana State University - Northern');
insert into user_list (name, college) values ('Carie Old', 'Sarah Lawrence College');
insert into user_list (name, college) values ('Minda Connock', 'Université des Montagnes');
insert into user_list (name, college) values ('Annelise Pritchett', 'Southwestern College Santa Fe');
insert into user_list (name, college) values ('Cletus Timbridge', 'Hyogo University');
insert into user_list (name, college) values ('Rancell Fonzo', 'Mazandaran University of Medical Science');
insert into user_list (name, college) values ('Denver Adlington', 'North Eastern Hill University');
insert into user_list (name, college) values ('Alyss Karolewski', 'Roanoke College');
insert into user_list (name, college) values ('Justina Gossage', 'University of Cagliari');
insert into user_list (name, college) values ('Mycah Vicarey', 'Saitama Institute of Technology');
insert into user_list (name, college) values ('Millie Fairleigh', 'DIPLOMA-Fachhochschule Ölsnitz/Vogtland');
insert into user_list (name, college) values ('Manon Wase', 'University of Queensland');
insert into user_list (name, college) values ('Kimberlyn Sabati', 'Tsukuba University');
insert into user_list (name, college) values ('Ax Heyfield', 'Petro Mohyla Black Sea State University');
insert into user_list (name, college) values ('Marti Savatier', 'University of the East, Ramon Magsaysay Memorial Medical Center');
insert into user_list (name, college) values ('Lauretta Stallon', 'Necmettin Erbakan University');
insert into user_list (name, college) values ('Reinaldos Sancroft', 'Universidad Tecnologica "Vicente Perez Rosales"');
insert into user_list (name, college) values ('Jean Cosens', 'Universidad Valle del Momboy');
insert into user_list (name, college) values ('Mandel Pickthorne', 'Eastern University of Sri Lanka');
insert into user_list (name, college) values ('Papagena MacPike', 'Uttarakhand Open University ');
insert into user_list (name, college) values ('Francisco Matskiv', 'Universidad Nacional de Rosario');
insert into user_list (name, college) values ('Carlin Hacun', 'Nipissing University');
insert into user_list (name, college) values ('Werner Housen', 'Mandalay Technological University');
insert into user_list (name, college) values ('Tricia Jacombs', 'Universidad San Francisco de Quito');
insert into user_list (name, college) values ('Antone Daice', 'Universidad Don Vasco');
insert into user_list (name, college) values ('Roger Tinniswood', 'Universidade Tiradentes');
insert into user_list (name, college) values ('Atalanta Ryman', 'Prempeh College');
insert into user_list (name, college) values ('Alaine Dilston', 'Universidade de Cruz Alta');
insert into user_list (name, college) values ('Edan MacDearmaid', 'Universidad Autónoma del Caribe');
insert into user_list (name, college) values ('Angie Bridgwater', 'Himeji Dokkyo University');
insert into user_list (name, college) values ('Yurik Charpling', 'Fernuniversität Gesamthochschule Hagen');
insert into user_list (name, college) values ('Deloria Woollaston', 'St. Petersburg State Polytechnical University');
insert into user_list (name, college) values ('Anna-diane Phorsby', 'Eastern Asia University');
insert into user_list (name, college) values ('Jerrold Cicculi', 'Universidad la Concordia');
insert into user_list (name, college) values ('Brion Tolmie', 'Europa-Universität Viadrina Frankfurt (Oder)');
insert into user_list (name, college) values ('Lusa Musico', 'Immanuel Kant State University of Russia');
insert into user_list (name, college) values ('Allx Colleran', 'Ondo State University of Science and Technology');
insert into user_list (name, college) values ('Cindra Swayne', 'Amrita Vishwa Vidyapeetham (Deemed University)');
insert into user_list (name, college) values ('Caria Sheryne', 'Darul Ulum Islamic College');
insert into user_list (name, college) values ('Sadie Emloch', 'Texas College of Osteopathic Medicine');
insert into user_list (name, college) values ('Lisle Perdue', 'University of Texas Health Center at Tyler');
insert into user_list (name, college) values ('Sandie Leon', 'Arab Open University');
insert into user_list (name, college) values ('Cam Pebworth', 'University of Southern Indiana');
insert into user_list (name, college) values ('Loni Padrick', 'Fachhochschule Heilbronn, Hochschule für Technik und Wirtschaft');
insert into user_list (name, college) values ('Gusella Bowness', 'St. Joseph''s College of Maine');
insert into user_list (name, college) values ('Murielle Whimper', 'Free International University of Moldova');
insert into user_list (name, college) values ('Gamaliel Sanches', 'Hainan Normal University');
insert into user_list (name, college) values ('Barbra Gamwell', 'Heilongjiang Commercial University');
insert into user_list (name, college) values ('Ephrem Bourke', 'Northwood University');
insert into user_list (name, college) values ('Lenna Cathrae', 'Universidade Federal de Rondônia');
insert into user_list (name, college) values ('Tiebout Vagges', 'Pondicherry University');
insert into user_list (name, college) values ('Tally De Maria', 'Keiwa College');
insert into user_list (name, college) values ('Korney Maffetti', 'University of Kota');
insert into user_list (name, college) values ('Nerty Cleever', 'Ecole Nationale Supérieure des Mines de Paris');
insert into user_list (name, college) values ('Katie Kilcoyne', 'Lyndon State College');
insert into user_list (name, college) values ('Yoshiko Leroux', 'Ecole Catholique d''Arts & Metiers');
insert into user_list (name, college) values ('Gavan Castro', 'Najran University');
insert into user_list (name, college) values ('Bartolomeo Sallinger', 'Politeknik Negeri Semarang');
insert into user_list (name, college) values ('Collete Bulward', 'University of the Virgin Islands');
insert into user_list (name, college) values ('Aaron Kennewell', 'Centro Universitário de João Pessoa');
insert into user_list (name, college) values ('Mattias Romei', 'Edgewood College');
insert into user_list (name, college) values ('Merridie Pim', 'Korea National University of Education');
insert into user_list (name, college) values ('Myra Meckiff', 'Kanazawa College of Economics');
insert into user_list (name, college) values ('Kendricks Loosley', 'Ecole Nationale Supérieure de Biologie Appliquée à la Nutrition et à l''Alementation');
insert into user_list (name, college) values ('Marge Cothey', 'Chiba Institute of Technology');
insert into user_list (name, college) values ('Cole Branson', 'Universidad Luterana Salvadorena');
insert into user_list (name, college) values ('Rosco Blackborough', 'American College Of Dubai');
insert into user_list (name, college) values ('Wes Matushenko', 'Takhatmal Shrivallabh Homoeopathic Medical College');
insert into user_list (name, college) values ('Revkah Cash', 'Hebei University of Technology');
insert into user_list (name, college) values ('Nanice Issacov', 'Hong Bang University International');
insert into user_list (name, college) values ('Isa Ellwood', 'Hochschule für Bankwirtschaft (HfB), Private Fachhochschule der Bankakademie');
insert into user_list (name, college) values ('Grantley Garrals', 'Zia-ud-Din Medical University');
insert into user_list (name, college) values ('Erich Clausen', 'Truman State University');
insert into user_list (name, college) values ('Carola Tommeo', 'Grace College');
insert into user_list (name, college) values ('Yancey Dracey', 'Reitaku University');
insert into user_list (name, college) values ('Wilma Midford', 'Preston Institute of Management Sciences and Technology (PIMSAT)');
insert into user_list (name, college) values ('Muriel MacCarrick', 'University of NorthWest');
insert into user_list (name, college) values ('Beverley O''Lennane', 'Kyungpook National University');
insert into user_list (name, college) values ('Kittie Feye', 'Takarazuka University of Art and Design');
insert into user_list (name, college) values ('Hanny Grishakin', 'Ho Chi Minh City University of Social Sciences and Humanities');
insert into user_list (name, college) values ('Mason Fortey', 'Guilan University of Medical Sciences');
insert into user_list (name, college) values ('Jaquelyn Librey', 'Eastern Nazarene College');
insert into user_list (name, college) values ('Manfred Whaley', 'University of Detroit Mercy');
insert into user_list (name, college) values ('Chandler Giuroni', 'Azabu University');
insert into user_list (name, college) values ('Deeann Chittock', 'University of Economics Varna');
insert into user_list (name, college) values ('Sophie Vose', 'University of Miskolc');
insert into user_list (name, college) values ('Perceval Nipper', 'Cedarville College');
insert into user_list (name, college) values ('Jehanna Dimmack', 'Birjand University');
insert into user_list (name, college) values ('Arabella Pickles', 'Taejon National University of Technology');
insert into user_list (name, college) values ('Nye Hoyte', 'ITT Technical Institute Maitland');
insert into user_list (name, college) values ('Vivien Varfalameev', 'Wake Forest University');
insert into user_list (name, college) values ('Terese De Hoogh', 'Odlar Yurdu University');
insert into user_list (name, college) values ('Koren Jamson', 'Volgograd State Technical University');
insert into user_list (name, college) values ('Katinka Hambidge', 'Linguistic University of Nizhny Novgorod');
insert into user_list (name, college) values ('Garret Banton', 'University of Tasmania');
insert into user_list (name, college) values ('Goldie Bushell', 'State University of New York Downstate Medical Center');
insert into user_list (name, college) values ('Emily Kleimt', 'Ternopil State Ivan Pul''uj Technical University');
insert into user_list (name, college) values ('Arnold Rudyard', 'Iceland Academy of the Arts');
insert into user_list (name, college) values ('Karine L''oiseau', 'Hillsdale College');
insert into user_list (name, college) values ('Eulalie Morgen', 'Tunku Abdul Rahman Chinese College');
insert into user_list (name, college) values ('Zed Dawkins', 'Free University "Maria Santissima Assunta"');
insert into user_list (name, college) values ('Clerkclaude Haldane', 'Ritsumeikan University');
insert into user_list (name, college) values ('Janenna Jearum', 'Ecole Catholique d''Arts & Metiers');
insert into user_list (name, college) values ('Tammi East', 'Clarke College');
insert into user_list (name, college) values ('Keefer Boman', 'Georgetown University');
insert into user_list (name, college) values ('Stern Brusle', 'New Mexico Institute of Mining and Technology');
insert into user_list (name, college) values ('Domenic Peizer', 'Conservatorio del Tolima');
insert into user_list (name, college) values ('Abigale Farrimond', 'Salem State College');
insert into user_list (name, college) values ('Penni Linnitt', 'Technological University (Banmaw)');
insert into user_list (name, college) values ('Hattie Baptie', 'Suzhou University');
insert into user_list (name, college) values ('Guido Parcells', 'Xuzhou Normal University');
insert into user_list (name, college) values ('Viviene Stadden', 'George Fox University');
insert into user_list (name, college) values ('Liam Greensted', 'Andrews University');
insert into user_list (name, college) values ('Rurik Jacobs', 'Damanhour University');
insert into user_list (name, college) values ('Annetta Wisker', 'Faculdades Integradas Toledo');
insert into user_list (name, college) values ('Joletta Grundle', 'Azad Jammu and Kashmir University');
insert into user_list (name, college) values ('Eddy Strafford', 'Universidad Adolfo Ibáñez');
insert into user_list (name, college) values ('Athena De Ruggiero', 'Islamic Azad University, Mashhad');
insert into user_list (name, college) values ('Roma Kingescot', 'Universidad de Piura');
insert into user_list (name, college) values ('Brittani Bowden', 'Ohio Northern University');
insert into user_list (name, college) values ('Ericha Atton', 'Schiller International University, London');
insert into user_list (name, college) values ('Enrica Gresley', 'Corporación Educativa Mayor del Desarrollo "Simón Bolivar"');
insert into user_list (name, college) values ('Baron Faich', 'Dalhousie University');
insert into user_list (name, college) values ('Sher Lead', 'Universidade Metodista de Piracicaba');
insert into user_list (name, college) values ('Beverley Cruikshank', 'American Conservatory of Music');
insert into user_list (name, college) values ('Malva Cappell', 'Universität Duisburg-Essen');
insert into user_list (name, college) values ('Maryl Huskisson', 'Minsk State Linguistic University');
insert into user_list (name, college) values ('Erroll Emer', 'Technische Universität München');
insert into user_list (name, college) values ('Raye Gutch', 'University of Tromsø');
insert into user_list (name, college) values ('Jefferey Fenck', 'College of Visual Arts');
insert into user_list (name, college) values ('Onida Batty', 'Institute of Teachers Education, Tun Hussein Onn');
insert into user_list (name, college) values ('Danita Stott', 'University of Seychelles');
insert into user_list (name, college) values ('Ashlan Wickardt', 'Petrozavodsk State University');
insert into user_list (name, college) values ('Clea Brockie', 'College of St. Benedict and St. John''s University');
insert into user_list (name, college) values ('Hyacintha Bamlett', 'Cheljabinsk State University');
insert into user_list (name, college) values ('Dallas Danigel', 'Kung Shan Institute of Technology');
insert into user_list (name, college) values ('Dill Bater', 'Wayo Women''s University');
insert into user_list (name, college) values ('Holly Harmond', 'Haverford College');
insert into user_list (name, college) values ('Broddie Minter', 'University of Latvia');
insert into user_list (name, college) values ('Greggory Nicklin', 'Wisconsin School of Professional Psychology');
insert into user_list (name, college) values ('Wilfred Newrick', 'Universidade do Estado do Rio Grande do Norte');
insert into user_list (name, college) values ('Dolph Tulip', 'Henan Univeristy');
insert into user_list (name, college) values ('Maximilianus Heifer', 'Thunderbird School of Global Management');
insert into user_list (name, college) values ('Coleman O'' Shea', 'Ecole Nationale Supérieure des Mines d''Alès');
insert into user_list (name, college) values ('Magnum Tressler', 'Uttarakhand Open University ');
insert into user_list (name, college) values ('Darryl Fielding', 'Central Queensland University');
insert into user_list (name, college) values ('Jaime Sherrett', 'Yaroslavl State Medical Academy');
insert into user_list (name, college) values ('Rori McConville', 'Rovaniemi University of Applied Sciences');
insert into user_list (name, college) values ('Hank Bulteel', 'Universitas Muslim Indonesia');
insert into user_list (name, college) values ('Anderson Sherrott', 'Islamic Azad University, Mahshar');
insert into user_list (name, college) values ('Cindie Savin', 'Bahrain Polytechnic');
insert into user_list (name, college) values ('Keriann Rosier', 'Universidad Nacional San Luis Gonzaga');
insert into user_list (name, college) values ('Shandee Flintiff', 'Winona State University');
insert into user_list (name, college) values ('Trenna Bemand', 'Ecole Supérieure de Commerce de Lyon');
insert into user_list (name, college) values ('Laverna Braz', 'University "Aurel Vlaicu" Arad');
insert into user_list (name, college) values ('Gherardo Spata', 'Northwestern College St. Paul');
insert into user_list (name, college) values ('Kirby Harome', 'Berry College');
insert into user_list (name, college) values ('Glory Ianniello', 'University of Maine, Augusta');
insert into user_list (name, college) values ('Ruttger Raoult', 'Beijing Normal University');
insert into user_list (name, college) values ('Cass Passo', 'Koshien University');
insert into user_list (name, college) values ('Joan Goodspeed', 'Universidad Autónoma de la Ciudad de México');
insert into user_list (name, college) values ('Amandy Betteson', 'University of Nebraska (System)');
insert into user_list (name, college) values ('Jacky Sparshutt', 'Universidade Federal de Santa Catarina');
insert into user_list (name, college) values ('Rorie McAne', 'Taibah University');
insert into user_list (name, college) values ('Inez O''Doireidh', 'Shandong University of Triaditional Chinese Medicine');
insert into user_list (name, college) values ('Rosana Critoph', 'University of Medicine and Pharmacy of Iasi');
insert into user_list (name, college) values ('Aristotle Readwing', 'La Trobe University');
insert into user_list (name, college) values ('Hilliard Arthy', 'Calumet College of St. Joseph');
insert into user_list (name, college) values ('Tomasine Matczak', 'Université Kofi Annan');
insert into user_list (name, college) values ('Ezechiel Gurys', 'South China Agricultural University');
insert into user_list (name, college) values ('Harv Leverson', 'Universitas Pekalongan');
insert into user_list (name, college) values ('Marcile Swanston', 'Coastal Carolina University');
insert into user_list (name, college) values ('Camille Tine', 'Universidad Pontificia Comillas');
insert into user_list (name, college) values ('Bekki Bufton', 'University of East Asia');
insert into user_list (name, college) values ('Iorgo Azemar', 'Universidad Federico Henríquez y Carvajal');
insert into user_list (name, college) values ('Kane Tudge', 'University of Pennsylvania');
insert into user_list (name, college) values ('Olin Pablo', 'Halic University');
insert into user_list (name, college) values ('Syd Harses', 'Polytechnic Institute of Bari');
insert into user_list (name, college) values ('Anderea Nestoruk', 'University of Hyderabad');
insert into user_list (name, college) values ('Tresa Sydenham', 'Xi''an University of Architecture and Technology');
insert into user_list (name, college) values ('Zak Scarratt', 'AISTEDA');
insert into user_list (name, college) values ('Brigg Bassindale', 'Holy Apostles College');
insert into user_list (name, college) values ('Heather Kearford', 'Nipissing University');
insert into user_list (name, college) values ('Donovan Briars', 'Universidade Católica de Goiás');
insert into user_list (name, college) values ('Tabby Cracknell', 'Lafayette College');
insert into user_list (name, college) values ('Tamera Hallum', 'Timirjazev Moscow Academy of Agricultutre');
insert into user_list (name, college) values ('Rhona Ogglebie', 'Fundación Universitaria de Boyacá');
insert into user_list (name, college) values ('Gregorius Pollendine', 'Université Chouaib Doukkali');
insert into user_list (name, college) values ('Livia Hyde', 'Moscow State Technical University of Civil Aviation');
insert into user_list (name, college) values ('Sutherlan Weafer', 'Niger Delta University');
insert into user_list (name, college) values ('Cosette Juza', 'Liaoning Technical University');
insert into user_list (name, college) values ('Ariadne Borrett', 'Armed Forces Academy of General Milan Rastislav Štefánik');
insert into user_list (name, college) values ('Tremaine Gotobed', 'Segi University College');
insert into user_list (name, college) values ('Gladys Everit', 'Shanghai Institue of Foreign Trade');
insert into user_list (name, college) values ('Vinny Mountcastle', 'Petrozavodsk State University');
insert into user_list (name, college) values ('Koenraad Laurens', 'Hochschule Albstadt-Sigmaringen');
insert into user_list (name, college) values ('Kaja Maulden', 'Fiji National University ');
insert into user_list (name, college) values ('Gretal Bantock', 'Universidad Metropolitana');
insert into user_list (name, college) values ('Fernanda Renney', 'Moscow State University of Ecological Engineering');
insert into user_list (name, college) values ('Waverly Clifforth', 'Worcester State College');
insert into user_list (name, college) values ('Amandy Comberbeach', 'Aomori Public College');
insert into user_list (name, college) values ('Maegan Winterbottom', 'Universidad Iberoamericana, Campus León');
insert into user_list (name, college) values ('Faythe Loach', 'University of Southern Denmark');
insert into user_list (name, college) values ('Aura Killich', 'Amman Arab University for Higher Studies');
insert into user_list (name, college) values ('Elia Clorley', 'University of Palermo');
insert into user_list (name, college) values ('Danica Clappison', 'Mordovian State University');
insert into user_list (name, college) values ('Carlee Ennew', 'Indiana University at Kokomo');
insert into user_list (name, college) values ('Morissa Plover', 'Universidad José Cecilio del Valle');
insert into user_list (name, college) values ('Kippy Dinsmore', 'University of South Dakota');
insert into user_list (name, college) values ('Ahmed Boutton', 'Hoseo University');
insert into user_list (name, college) values ('Sybille Jakes', 'Bluefield College');
insert into user_list (name, college) values ('Margalit Brunotti', 'Sanaag University of Science and Technology');
insert into user_list (name, college) values ('Terri Slucock', 'Jodhpur National University');
insert into user_list (name, college) values ('Morena Scorrer', 'Yarmouk Private University ');
insert into user_list (name, college) values ('Joyann Leuty', 'Ludwig-Maximilians-Universität München');
insert into user_list (name, college) values ('Kimble Mixhel', 'Zhejiang University');
insert into user_list (name, college) values ('Darcey Puckrin', 'Argosy University - Hawaii');
insert into user_list (name, college) values ('Cassius Palfree', 'Cyprus University of Technology');
insert into user_list (name, college) values ('Wilmer Hurley', 'King Mongkut''s University of Technology Ladkrabang');
insert into user_list (name, college) values ('Salli Hannaby', 'Swedish School of Economics and Business Administration, Finland');
insert into user_list (name, college) values ('June Dawidsohn', 'Universidad de Ciencias Aplicadas y Ambientales (UDCA)');
insert into user_list (name, college) values ('Eleen Newlands', 'Universitas Muhammadiyah Sumatra Utara');
insert into user_list (name, college) values ('Becka Vass', 'Universidad del Valle del Cauca');
insert into user_list (name, college) values ('Ulrick Cordoba', 'Knox College');
insert into user_list (name, college) values ('Ivette Woodcraft', 'Daugavpils University');
insert into user_list (name, college) values ('Herminia Faichnie', 'Calumet College of St. Joseph');
insert into user_list (name, college) values ('Dorthea Fratson', '1 December University of Alba Iulia');
insert into user_list (name, college) values ('Ardith Grooby', 'Guizhou Normal University');
insert into user_list (name, college) values ('Keely Itzkovsky', 'Pitzer College');
insert into user_list (name, college) values ('Edd Wipper', 'Rice University');
insert into user_list (name, college) values ('Linc Kiossel', 'Keiwa College');
insert into user_list (name, college) values ('Charlot Dibbe', 'Université de Tunis');
insert into user_list (name, college) values ('Mozes Rockall', 'Hyrcania Institute of Higher Education');
insert into user_list (name, college) values ('Sosanna Priver', 'Tokyo Gakugei University');
insert into user_list (name, college) values ('Devon Derr', 'Universidad de Las Palmas de Gran Canaria');
insert into user_list (name, college) values ('Helenka Whitehorne', 'Sumgait State University');
insert into user_list (name, college) values ('Norbert Albasiny', 'Universidad Nacional Federico Villarreal');
insert into user_list (name, college) values ('Modesta McLardie', 'Emerson College');
insert into user_list (name, college) values ('Wendye Bonafant', 'University of Dhaka');
insert into user_list (name, college) values ('Gian Mordey', 'International Academy of  Merchandising and Design Tampa');
insert into user_list (name, college) values ('Josie Fellow', 'Polotsk State University');
insert into user_list (name, college) values ('Alan Able', 'Ecole Nationale d''Ingénieurs des Travaux Agricoles de Clermont-Ferrand');
insert into user_list (name, college) values ('Rogers Brammall', 'Universitas Bunda Mulia Jakarta');
insert into user_list (name, college) values ('Rey Grimbleby', 'Andrew Jackson University');
insert into user_list (name, college) values ('Gothart Fodden', 'Tennessee State University');
insert into user_list (name, college) values ('Sylas Pryor', 'Ternopil Academy of National Economy');
insert into user_list (name, college) values ('Wyndham Malyon', 'University of St. Michael''s College');
insert into user_list (name, college) values ('Sherlock Dubois', 'University of Bath');
insert into user_list (name, college) values ('Aurel Parratt', 'Hosei University');
insert into user_list (name, college) values ('Cornelle Depport', 'Colorado Technical University');
insert into user_list (name, college) values ('Beverlee Hurleston', 'University of the East, Manila');
insert into user_list (name, college) values ('Elyssa Tredget', 'Florida Atlantic University');
insert into user_list (name, college) values ('Baillie Hantusch', 'University of Brunei Darussalam');
insert into user_list (name, college) values ('Conn Bog', 'Universität Köln');
insert into user_list (name, college) values ('Eolanda Holsey', 'Fakir Mohan University');
insert into user_list (name, college) values ('Carroll Reynoollds', 'Troy University, Phenix City');
insert into user_list (name, college) values ('Gilbertina Jickells', 'Yunnan Normal University');
insert into user_list (name, college) values ('Bamby Necrews', 'Tufts University');
insert into user_list (name, college) values ('Barclay Badger', 'University of Management and Marketing');
insert into user_list (name, college) values ('Nate Orwin', 'Liceo de Cagayan University');
insert into user_list (name, college) values ('Mallory Spratley', 'Central Mindanao University');
insert into user_list (name, college) values ('Stanley Roussell', 'Columbus University');
insert into user_list (name, college) values ('Desirae Hughland', 'University of Balochistan');
insert into user_list (name, college) values ('Elyse Steere', 'Universidad José Antonio Páez');
insert into user_list (name, college) values ('Grissel Hawkyens', 'Shiga University of Medical Science');
insert into user_list (name, college) values ('Nanci Greenside', 'Universidad Internacional de Andalucía');
insert into user_list (name, college) values ('Hermie Williamson', 'Dnepropetrovsk National University');
insert into user_list (name, college) values ('Dulce Gormley', 'Voronezh State Medical Academy');
insert into user_list (name, college) values ('Brocky Rosenblath', 'Shaheed Beheshti University of Medical Sciences');
insert into user_list (name, college) values ('Francesco Paoli', 'Tianjin University of Commerce');
insert into user_list (name, college) values ('Ginger MacFie', 'State University of New York College at Old Westbury');
insert into user_list (name, college) values ('Malynda Verbeke', 'University of Iowa');
insert into user_list (name, college) values ('Rikki Chillingsworth', 'Ecole Supérieure d''Electricité');
insert into user_list (name, college) values ('Josey Phripp', 'Islamic Azad University, Tehran Medical');
insert into user_list (name, college) values ('Bartholomeo Klimsch', 'South-West University "Neofit Rilski"');
insert into user_list (name, college) values ('Darcey Worsnip', 'University of Fiji');
insert into user_list (name, college) values ('Gualterio Grayshan', 'Universidad Monsenor Oscar Arnulfo Romeo');
insert into user_list (name, college) values ('Carl Buggs', 'Maria Grzegorzewska College for Special Education');
insert into user_list (name, college) values ('Gretchen Baelde', 'Hertie School of Governance');
insert into user_list (name, college) values ('Tory Diloway', 'St. Petersburg State Pediatric Medical Academy');
insert into user_list (name, college) values ('Nadine Carder', 'Musashino Women''s University');
insert into user_list (name, college) values ('Sergio Morgan', 'Rochester Institute of Technology, Dubai');
insert into user_list (name, college) values ('Sandy Shobbrook', 'Doane College');
insert into user_list (name, college) values ('Bernadina Glassopp', 'Thomas College Maine');
insert into user_list (name, college) values ('Bathsheba Druitt', 'Southwest Jiaotong University');
insert into user_list (name, college) values ('Oswald Frears', 'Moscow External University of the Humanities');
insert into user_list (name, college) values ('Dee Clamp', 'Shaheed Beheshti University of Medical Sciences');
insert into user_list (name, college) values ('Gennifer Laugharne', 'Southern Cross University');
insert into user_list (name, college) values ('Noach June', 'Felician College');
insert into user_list (name, college) values ('Talbert Valentine', 'Lindsey Wilson College');
insert into user_list (name, college) values ('Saul Joyes', 'Universidad del Noreste');
insert into user_list (name, college) values ('Justis Bosson', 'University of the Sacred Heart Tokyo');
insert into user_list (name, college) values ('Claretta Trodler', 'Chandra Shekhar Azad University of Agriculture and Technology');
insert into user_list (name, college) values ('Jenilee Labitt', 'Bharathidasan University');
insert into user_list (name, college) values ('Filide Howselee', 'Oakton Community College');
insert into user_list (name, college) values ('Gwenette Goldwater', 'Stratford College London');
insert into user_list (name, college) values ('Gonzales Eglinton', 'University of Guelph');
insert into user_list (name, college) values ('Elli Dureden', 'Fachhochschule Vorarlberg');
insert into user_list (name, college) values ('Dulsea Vivers', 'National Museum Institute of History of Art, Conservation and Museology');
insert into user_list (name, college) values ('Yorgo Harroway', 'Florida Southern College');
insert into user_list (name, college) values ('Mina Waudby', 'Federal University of Technology, Yola');
insert into user_list (name, college) values ('Fredrika Cunniff', 'Ecole Supérieure des Sciences Economiques et Commerciales');
insert into user_list (name, college) values ('Abie Fouracres', 'Instituto Politécnico de Bragança');
insert into user_list (name, college) values ('Gar Van T''Hoog', 'Centenary College');
insert into user_list (name, college) values ('Caitrin Pollastrone', 'International Institute for Geo - Information Science and Earth Observation');
insert into user_list (name, college) values ('Sheilah Van de Velde', 'Universidade do Estado do Rio de Janeiro');
insert into user_list (name, college) values ('Chip Kelemen', 'Adventist University of Central Africa');
insert into user_list (name, college) values ('Ursuline Gluyus', 'Anton de Kom University');
insert into user_list (name, college) values ('Orelee Freckingham', 'Institute of Teachers Education, Darul Aman');
insert into user_list (name, college) values ('Guenna Aslet', 'Fachhochschule Krems');
insert into user_list (name, college) values ('Cecil Rodge', 'Konyang University');
insert into user_list (name, college) values ('Mercy Hurler', 'Shizuoka University');
insert into user_list (name, college) values ('Sisile Doppler', 'Université de Toliary');
insert into user_list (name, college) values ('Audrey Covington', 'South-East Asia University');
insert into user_list (name, college) values ('Gerladina Easdon', 'Universidad Técnica de Manabí');
insert into user_list (name, college) values ('Evita Bursell', 'Embry Riddle Aeronautical University, Prescott');
insert into user_list (name, college) values ('Christoforo Sadlier', 'Universidad Simón Bolivar');
insert into user_list (name, college) values ('Beryl Daniaud', 'Universidad Dominico-Americana');
insert into user_list (name, college) values ('Tracy Angus', 'Fukui University of Technology');
insert into user_list (name, college) values ('Ryann Caillou', 'Georgia State University');
insert into user_list (name, college) values ('Bridie Bovingdon', 'Olive-Harvey College');
insert into user_list (name, college) values ('Jess Craig', 'Wayo Women''s University');
insert into user_list (name, college) values ('Malanie Pringuer', 'Universidad Tecnológica de Honduras');
insert into user_list (name, college) values ('Benedicta Swabey', 'Fundación Universitaria del Area Andina. Sede Pereira');
insert into user_list (name, college) values ('Georgeanna Schwand', 'Northwest Christian College');
insert into user_list (name, college) values ('Rozele Rubberts', 'Xi''an University of Architecture and Technology');
